# Nix flake for Kizurium Translator (NixOS / nix profile / nix run).
#
# Runtime needs Wayland + grim + gtk4-layer-shell (+ quickshell for region
# select); no particular compositor is required.
#
# Quick start:
#   nix run .#
#   nix run .# -- --doctor
#   nix profile add .#kizurium-translator
{
  description = "Kizurium Translator — Wayland OCR overlay translator";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs =
    { self, nixpkgs }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = false;
          };
          python = pkgs.python3;
          kizurium-translator = python.pkgs.buildPythonApplication {
            pname = "kizurium-translator";
            version = "1.1.0";
            pyproject = true;
            src = pkgs.lib.cleanSourceWith {
              src = self;
              filter =
                path: type:
                let
                  base = baseNameOf path;
                in
                # A `.gitignore` entry does not keep a file out of a
                # `path:` or `tarball:` source, so the built package is dropped
                # here as well: through a git flake it is untracked, through
                # `path:` it is 5 MB of binary that ships in every derivation.
                !(builtins.elem base [
                  ".git"
                  ".venv"
                  ".local"
                  "result"
                  "__pycache__"
                  ".pytest_cache"
                  ".ruff_cache"
                  ".mypy_cache"
                  "dist"
                ])
                && !(pkgs.lib.hasSuffix ".pkg.tar.zst" base)
                && !(pkgs.lib.hasSuffix ".whl" base);
            };

            build-system = with python.pkgs; [ hatchling ];

            dependencies = with python.pkgs; [
              pillow
              numpy
              pytesseract
              requests
              pygobject3
              pycairo
              # Same quality path as Arch ./install.sh defaults (RapidOCR).
              rapidocr
              onnxruntime
            ];

            nativeBuildInputs = with pkgs; [
              wrapGAppsHook4
              gobject-introspection
              pkg-config
              makeWrapper
            ];

            buildInputs = with pkgs; [
              gtk4
              gtk4-layer-shell
              libnotify
            ];

            # The suite runs headless - it needs no compositor - but pytest and
            # the fixtures it reads are not build inputs, so the tests are run
            # by `checks` below rather than here.
            doCheck = false;

            # grim, slurp, wl-copy, tesseract and quickshell are separate
            # programs the overlay shells out to, so a profile that holds only
            # this package would not find them. `makeWrapperArgs` reaches the
            # wrapper buildPythonApplication already writes - the old postFixup
            # called wrapProgram on that finished wrapper, which nested a third
            # exec on every start.
            makeWrapperArgs = [
              "--prefix PATH : ${
                pkgs.lib.makeBinPath (with pkgs; [
                  grim
                  slurp
                  wl-clipboard
                  tesseract
                  quickshell
                  libnotify
                  aria2
                ])
              }"
              # Gtk4LayerShell is dlopened by name. RPATH cannot express it and
              # wrapGAppsHook4 does not cover a dlopen, so the two libraries go
              # on LD_LIBRARY_PATH - narrowly, for this binary only.
              "--prefix LD_LIBRARY_PATH : ${
                pkgs.lib.makeLibraryPath (with pkgs; [ gtk4-layer-shell gtk4 ])
              }"
            ];

            # Without a .desktop and an icon the binary is installed but has
            # no menu entry. assets/translator.png is a 946x504 screenshot and
            # cannot serve as one; assets/icons/ holds the square 256px icon,
            # generated by scripts/make_icon.py.
            #
            # postInstall, not installPhase: buildPythonApplication installs the
            # wheel in its own installPhase, and assigning one replaces it. The
            # package then built to a store path with share/ and no bin/, and
            # `nix run` failed with the binary missing.
            postInstall = ''
              install -Dm644 $src/assets/kizurium-translator.desktop \
                $out/share/applications/kizurium-translator.desktop
              install -Dm644 $src/assets/icons/kizurium-translator.png \
                $out/share/icons/hicolor/256x256/apps/kizurium-translator.png
            '';

            meta = with pkgs.lib; {
              description = "Translate text on screen via OCR and a Wayland layer-shell overlay";
              homepage = "https://github.com/Kizuchann/kizurium-translator";
              license = licenses.agpl3Plus;
              platforms = platforms.linux;
              mainProgram = "kizurium-translator";
            };
          };
        in
        {
          default = kizurium-translator;
          kizurium-translator = kizurium-translator;
        }
      );

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${self.packages.${system}.default}/bin/kizurium-translator";
          meta.description =
            "Translate text on screen via OCR and a Wayland layer-shell overlay";
        };
      });

      # Suggested system packages for NixOS (import in configuration).
      # Not a full NixOS module — keeps the flake simple and reviewable.
      nixosModules.default =
        {
          pkgs,
          lib,
          config,
          ...
        }:
        {
          options.programs.kizurium-translator = {
            enable = lib.mkEnableOption "Kizurium Translator (Wayland OCR overlay)";
            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.system}.default;
              description = "Package to install";
            };
          };
          config = lib.mkIf config.programs.kizurium-translator.enable {
            environment.systemPackages = [
              config.programs.kizurium-translator.package
              pkgs.grim
              pkgs.slurp
              pkgs.wl-clipboard
              pkgs.tesseract
              pkgs.quickshell
              pkgs.gtk4
              pkgs.gtk4-layer-shell
              pkgs.aria2
            ];
            # eng/rus/jpn tessdata — package set varies by nixpkgs; users may
            # also set TESSDATA_PREFIX. Doctor will report missing langs.
          };
        };

      # `checks` is what `nix flake check` runs, and until this existed the flake
      # had no checks at all: `nix flake check` passed without looking at a line
      # of the project. The suite needs no compositor - it runs headless - so it
      # is wired in here instead of leaving `doCheck` false with nothing behind
      # it.
      checks = forAllSystems (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            config.allowUnfree = false;
          };
          python = pkgs.python3;
          # Gtk is reached through gobject-introspection at runtime, and a
          # typelib is found by GI_TYPELIB_PATH rather than by a linker. The
          # list is the one wrapGAppsHook would build for this binary, written
          # out because `nix flake check` runs pytest inside a build where the
          # hook does not apply.
          typelibs = with pkgs; [
            gtk4
            gtk4-layer-shell
            glib
            gobject-introspection
            graphene
            gdk-pixbuf
            pango
            harfbuzz
            cairo
          ];
          # `makeSearchPathOutput output subDir` resolves the output and appends
          # the subdirectory, so the lib directory belongs in `subDir`. Spelling
          # it `makeSearchPathOutput "lib" "girepository-1.0"` reads correctly and
          # yields a path that exists but holds no typelibs. Checked against
          # nixpkgs lib/strings.nix:606 rather than assumed.
          typelibPath =
            pkgs.lib.makeSearchPathOutput "out" "lib/girepository-1.0" typelibs;
          libPath = pkgs.lib.makeLibraryPath typelibs;
        in
        {
          tests = python.pkgs.buildPythonApplication {
            pname = "kizurium-translator-tests";
            version = "1.1.0";
            pyproject = true;
            src = self;
            build-system = with python.pkgs; [ hatchling ];
            # The suite imports the package and its dependencies, so they have to
            # be here whether or not a wheel is installed. Without them the
            # runtime-deps hook fails before checkPhase is ever reached.
            dependencies = with python.pkgs; [
              pillow
              numpy
              pytesseract
              requests
              pygobject3
              pycairo
            ];
            # python.pkgs has pytest but not the GObject stack; that lives in pkgs.
            nativeBuildInputs = with python.pkgs; [ pytest ]
              ++ (with pkgs; [
                gtk4
                gtk4-layer-shell
                gobject-introspection
                tesseract
                # The build sandbox has no /bin, and the suite does shell out
                # to /bin/true and friends in a few places.
                coreutils
                # selector.select_region refuses to run without a shell to
                # start, and the selector tests exercise that refusal path, so
                # the check needs the binary they are looking for.
                quickshell
                bash
                grim
                wl-clipboard
              ]);
            doCheck = true;
            # The paths are interpolated here, not inside the '' string: a ${}
            # inside one is read by nix first, and handing an interpolation
            # function to `export` is the error this shape produces.
            checkPhase = ''
              runHook preCheck
              # The sandbox points HOME at /homeless-shelter, which does not
              # exist and cannot be created; 98 tests resolve the default data
              # directory under it and fail on open().
              export HOME="$TMPDIR"
              export PYTHONPATH="$PWD/src:$PYTHONPATH"
              export GI_TYPELIB_PATH="${typelibPath}"
              export LD_LIBRARY_PATH="${libPath}"
              pytest -q --tb=short
              runHook postCheck
            '';
            # Nothing to install: the tests read the source tree above.
            dontInstall = true;
          };
        }
      );

      formatter = forAllSystems (system: nixpkgs.legacyPackages.${system}.nixfmt);
    };
}
