"""Разбор растра на блоки: колонки, абзацы, служебные строки.

Реэкспорт явный: звёздочка не достаёт имена с подчёркиванием, а тесты
пользуются ими. Список строится разбором модулей, а не пишется руками -
рукописный список однажды разошёлся с кодом и уронил импорт соседнего
пакета вместо своего.
"""

from __future__ import annotations

from .grouping import (  # noqa: F401
    _COL_OCR_CACHE,
    _COL_OCR_CACHE_TTL,
    _flanked_by_columns,
    _merge_flow,
    box_crosses_gutter,
    column_bounds_from_centers,
    column_x_bounds,
    extract_vn_dialogue_from_band,
    filter_game_ui_lines,
    finalize_web_column_lines,
    gap_hits_gutter,
    image_column_gutters,
    is_desktop_chrome,
    is_known_gameplay_hud_phrase,
    is_menu_or_nav_line,
    is_mostly_russian,
    is_mostly_target,
    is_static_ui_overlay,
    looks_like_panel_body_line,
    looks_like_section_header,
    merge_paragraphs,
    normalize_column_bounds,
    page_column_gutters,
    split_button_rows,
    split_cross_column_merges,
    split_false_nav_merges,
    split_leading_name,
    split_text_by_segment_widths,
    split_title_banner_merges,
    split_vn_speaker_line,
    stitch_paragraph_lines,
    stitch_same_baseline,
    stitch_ui_body_paragraphs,
    stitch_word_gaps,
)
from .name_gap import (  # noqa: F401
    NAME_DIALOGUE_GAP_MIN_PX,
    annotate_side_by_side_name_body,
    horizontal_gap_px,
    is_name_dialogue_side_pair,
    name_dialogue_gap_threshold,
    should_refuse_merge_for_name_gap,
)

__all__ = [
    "NAME_DIALOGUE_GAP_MIN_PX",
    "_COL_OCR_CACHE",
    "_COL_OCR_CACHE_TTL",
    "_flanked_by_columns",
    "_merge_flow",
    "annotate_side_by_side_name_body",
    "box_crosses_gutter",
    "column_bounds_from_centers",
    "column_x_bounds",
    "extract_vn_dialogue_from_band",
    "filter_game_ui_lines",
    "finalize_web_column_lines",
    "gap_hits_gutter",
    "horizontal_gap_px",
    "image_column_gutters",
    "is_desktop_chrome",
    "is_known_gameplay_hud_phrase",
    "is_menu_or_nav_line",
    "is_mostly_russian",
    "is_mostly_target",
    "is_name_dialogue_side_pair",
    "is_static_ui_overlay",
    "looks_like_panel_body_line",
    "looks_like_section_header",
    "merge_paragraphs",
    "name_dialogue_gap_threshold",
    "normalize_column_bounds",
    "page_column_gutters",
    "should_refuse_merge_for_name_gap",
    "split_button_rows",
    "split_cross_column_merges",
    "split_false_nav_merges",
    "split_leading_name",
    "split_text_by_segment_widths",
    "split_title_banner_merges",
    "split_vn_speaker_line",
    "stitch_paragraph_lines",
    "stitch_same_baseline",
    "stitch_ui_body_paragraphs",
    "stitch_word_gaps",
]
